// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Championships_ChipSets_Seasons : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "championships",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    owner_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    default_buy_in = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    default_rebuy = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    enforce_defaults = table.Column<bool>(type: "boolean", nullable: false),
                    money_per_unit = table.Column<decimal>(type: "numeric(18,6)", precision: 18, scale: 6, nullable: false),
                    points_by_position = table.Column<List<int>>(type: "integer[]", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_championships", x => x.id);
                    table.ForeignKey(
                        name: "fk_championships_users_owner_id",
                        column: x => x.owner_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "championship_members",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    championship_id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    role = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    joined_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_championship_members", x => x.id);
                    table.ForeignKey(
                        name: "fk_championship_members_championships_championship_id",
                        column: x => x.championship_id,
                        principalSchema: "public",
                        principalTable: "championships",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_championship_members_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "chip_sets",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    championship_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_chip_sets", x => x.id);
                    table.ForeignKey(
                        name: "fk_chip_sets_championships_championship_id",
                        column: x => x.championship_id,
                        principalSchema: "public",
                        principalTable: "championships",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "invites",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    championship_id = table.Column<Guid>(type: "uuid", nullable: false),
                    code = table.Column<string>(type: "character varying(6)", maxLength: 6, nullable: false),
                    role = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    created_by = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    expires_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    max_uses = table.Column<int>(type: "integer", nullable: true),
                    uses = table.Column<int>(type: "integer", nullable: false),
                    is_revoked = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_invites", x => x.id);
                    table.ForeignKey(
                        name: "fk_invites_championships_championship_id",
                        column: x => x.championship_id,
                        principalSchema: "public",
                        principalTable: "championships",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "seasons",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    championship_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(60)", maxLength: 60, nullable: false),
                    starts_on = table.Column<DateOnly>(type: "date", nullable: false),
                    ends_on = table.Column<DateOnly>(type: "date", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_seasons", x => x.id);
                    table.ForeignKey(
                        name: "fk_seasons_championships_championship_id",
                        column: x => x.championship_id,
                        principalSchema: "public",
                        principalTable: "championships",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "chip_denominations",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    chip_set_id = table.Column<Guid>(type: "uuid", nullable: false),
                    face_value = table.Column<int>(type: "integer", nullable: false),
                    effective_value = table.Column<int>(type: "integer", nullable: false),
                    quantity = table.Column<int>(type: "integer", nullable: false),
                    colour = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_chip_denominations", x => x.id);
                    table.ForeignKey(
                        name: "fk_chip_denominations_chip_sets_chip_set_id",
                        column: x => x.chip_set_id,
                        principalSchema: "public",
                        principalTable: "chip_sets",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_championship_members_championship_id_user_id",
                schema: "public",
                table: "championship_members",
                columns: new[] { "championship_id", "user_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_championship_members_user_id",
                schema: "public",
                table: "championship_members",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_championships_owner_id",
                schema: "public",
                table: "championships",
                column: "owner_id");

            migrationBuilder.CreateIndex(
                name: "ix_chip_denominations_chip_set_id_face_value",
                schema: "public",
                table: "chip_denominations",
                columns: new[] { "chip_set_id", "face_value" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_chip_sets_championship_id",
                schema: "public",
                table: "chip_sets",
                column: "championship_id");

            migrationBuilder.CreateIndex(
                name: "ix_invites_championship_id",
                schema: "public",
                table: "invites",
                column: "championship_id");

            migrationBuilder.CreateIndex(
                name: "ix_invites_code",
                schema: "public",
                table: "invites",
                column: "code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_seasons_championship_id_starts_on",
                schema: "public",
                table: "seasons",
                columns: new[] { "championship_id", "starts_on" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "championship_members",
                schema: "public");

            migrationBuilder.DropTable(
                name: "chip_denominations",
                schema: "public");

            migrationBuilder.DropTable(
                name: "invites",
                schema: "public");

            migrationBuilder.DropTable(
                name: "seasons",
                schema: "public");

            migrationBuilder.DropTable(
                name: "chip_sets",
                schema: "public");

            migrationBuilder.DropTable(
                name: "championships",
                schema: "public");
        }
    }
}
