// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_StackAcknowledgement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "acknowledged_at_utc",
                schema: "public",
                table: "ledger_entries",
                type: "timestamp with time zone",
                nullable: true);

            // Everything already in the ledger was handed over long before this
            // column existed. Without the backfill, every player at every past
            // table would be met with a queue of notices for chips they counted
            // months ago.
            migrationBuilder.Sql(
                "UPDATE public.ledger_entries SET acknowledged_at_utc = created_at_utc;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "acknowledged_at_utc",
                schema: "public",
                table: "ledger_entries");
        }
    }
}
