// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_ChampionshipMember_DisplayOrder : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "display_order",
                schema: "public",
                table: "championship_members",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            // Every existing membership defaulted to 0 above, which would stack
            // every championship a user belongs to on top of each other. Give
            // each user's memberships a deterministic order instead, oldest
            // join first — the same order the list already read in before this
            // column existed.
            migrationBuilder.Sql("""
                UPDATE public.championship_members m
                SET display_order = sub.rn
                FROM (
                    SELECT id, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY joined_at_utc) - 1 AS rn
                    FROM public.championship_members
                ) sub
                WHERE m.id = sub.id;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "display_order",
                schema: "public",
                table: "championship_members");
        }
    }
}
