// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_LateEntryPolicy : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Added, backfilled, and only then is the old column dropped. The
            // scaffolded version dropped first and defaulted the new column to
            // zero, which would have quietly turned every table that allowed
            // late entry into one that refuses it.
            migrationBuilder.AddColumn<int>(
                name: "late_entry",
                schema: "public",
                table: "tables",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            // true -> Open (1), false -> Blocked (0). Nothing maps to Request:
            // it is a new answer nobody has given yet.
            migrationBuilder.Sql(
                """
                UPDATE public.tables
                SET late_entry = CASE WHEN allow_late_entry THEN 1 ELSE 0 END;
                """);

            migrationBuilder.DropColumn(
                name: "allow_late_entry",
                schema: "public",
                table: "tables");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "allow_late_entry",
                schema: "public",
                table: "tables",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            // Request has no boolean equivalent. It becomes true — a table that
            // was letting people ask is closer to one that lets them in than to
            // one that turns them away at the door.
            migrationBuilder.Sql(
                """
                UPDATE public.tables
                SET allow_late_entry = (late_entry <> 0);
                """);

            migrationBuilder.DropColumn(
                name: "late_entry",
                schema: "public",
                table: "tables");
        }
    }
}
