// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Tables_And_Ledger : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tables",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    championship_id = table.Column<Guid>(type: "uuid", nullable: false),
                    chip_set_id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    buy_in = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    rebuy = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    money_per_unit = table.Column<decimal>(type: "numeric(18,6)", precision: 18, scale: 6, nullable: false),
                    join_policy = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    allow_late_entry = table.Column<bool>(type: "boolean", nullable: false),
                    join_code = table.Column<string>(type: "character varying(6)", maxLength: 6, nullable: true),
                    small_chip_reserve = table.Column<int>(type: "integer", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    started_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    closed_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_tables", x => x.id);
                    table.ForeignKey(
                        name: "fk_tables_championships_championship_id",
                        column: x => x.championship_id,
                        principalSchema: "public",
                        principalTable: "championships",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_tables_chip_sets_chip_set_id",
                        column: x => x.chip_set_id,
                        principalSchema: "public",
                        principalTable: "chip_sets",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "table_players",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    table_id = table.Column<Guid>(type: "uuid", nullable: false),
                    user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
                    seat_order = table.Column<int>(type: "integer", nullable: false),
                    joined_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_table_players", x => x.id);
                    table.ForeignKey(
                        name: "fk_table_players_tables_table_id",
                        column: x => x.table_id,
                        principalSchema: "public",
                        principalTable: "tables",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_table_players_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ledger_entries",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    table_id = table.Column<Guid>(type: "uuid", nullable: false),
                    table_player_id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    money_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    counterparty_player_id = table.Column<Guid>(type: "uuid", nullable: true),
                    note = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    created_by = table.Column<Guid>(type: "uuid", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ledger_entries", x => x.id);
                    table.ForeignKey(
                        name: "fk_ledger_entries_table_players_counterparty_player_id",
                        column: x => x.counterparty_player_id,
                        principalSchema: "public",
                        principalTable: "table_players",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_ledger_entries_table_players_table_player_id",
                        column: x => x.table_player_id,
                        principalSchema: "public",
                        principalTable: "table_players",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_ledger_entries_tables_table_id",
                        column: x => x.table_id,
                        principalSchema: "public",
                        principalTable: "tables",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "ledger_entry_chips",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    ledger_entry_id = table.Column<Guid>(type: "uuid", nullable: false),
                    chip_denomination_id = table.Column<Guid>(type: "uuid", nullable: false),
                    quantity = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_ledger_entry_chips", x => x.id);
                    table.ForeignKey(
                        name: "fk_ledger_entry_chips_chip_denominations_chip_denomination_id",
                        column: x => x.chip_denomination_id,
                        principalSchema: "public",
                        principalTable: "chip_denominations",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_ledger_entry_chips_ledger_entries_ledger_entry_id",
                        column: x => x.ledger_entry_id,
                        principalSchema: "public",
                        principalTable: "ledger_entries",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_ledger_entries_counterparty_player_id",
                schema: "public",
                table: "ledger_entries",
                column: "counterparty_player_id");

            migrationBuilder.CreateIndex(
                name: "ix_ledger_entries_table_id",
                schema: "public",
                table: "ledger_entries",
                column: "table_id");

            migrationBuilder.CreateIndex(
                name: "ix_ledger_entries_table_player_id",
                schema: "public",
                table: "ledger_entries",
                column: "table_player_id");

            migrationBuilder.CreateIndex(
                name: "ix_ledger_entry_chips_chip_denomination_id",
                schema: "public",
                table: "ledger_entry_chips",
                column: "chip_denomination_id");

            migrationBuilder.CreateIndex(
                name: "ix_ledger_entry_chips_ledger_entry_id_chip_denomination_id",
                schema: "public",
                table: "ledger_entry_chips",
                columns: new[] { "ledger_entry_id", "chip_denomination_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_table_players_table_id_user_id",
                schema: "public",
                table: "table_players",
                columns: new[] { "table_id", "user_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_table_players_user_id",
                schema: "public",
                table: "table_players",
                column: "user_id");

            migrationBuilder.CreateIndex(
                name: "ix_tables_championship_id_status",
                schema: "public",
                table: "tables",
                columns: new[] { "championship_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_tables_chip_set_id",
                schema: "public",
                table: "tables",
                column: "chip_set_id");

            migrationBuilder.CreateIndex(
                name: "ix_tables_join_code",
                schema: "public",
                table: "tables",
                column: "join_code",
                unique: true,
                filter: "join_code IS NOT NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ledger_entry_chips",
                schema: "public");

            migrationBuilder.DropTable(
                name: "ledger_entries",
                schema: "public");

            migrationBuilder.DropTable(
                name: "table_players",
                schema: "public");

            migrationBuilder.DropTable(
                name: "tables",
                schema: "public");
        }
    }
}
