// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_BlindLevels_And_Clock : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "blind_levels",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    table_id = table.Column<Guid>(type: "uuid", nullable: false),
                    order = table.Column<int>(type: "integer", nullable: false),
                    small_blind = table.Column<int>(type: "integer", nullable: false),
                    big_blind = table.Column<int>(type: "integer", nullable: false),
                    ante = table.Column<int>(type: "integer", nullable: false),
                    duration_seconds = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_blind_levels", x => x.id);
                    table.ForeignKey(
                        name: "fk_blind_levels_tables_table_id",
                        column: x => x.table_id,
                        principalSchema: "public",
                        principalTable: "tables",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "table_clocks",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    table_id = table.Column<Guid>(type: "uuid", nullable: false),
                    current_level = table.Column<int>(type: "integer", nullable: false),
                    level_started_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    paused_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    accumulated_pause_seconds = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_table_clocks", x => x.id);
                    table.ForeignKey(
                        name: "fk_table_clocks_tables_table_id",
                        column: x => x.table_id,
                        principalSchema: "public",
                        principalTable: "tables",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_blind_levels_table_id_order",
                schema: "public",
                table: "blind_levels",
                columns: new[] { "table_id", "order" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_table_clocks_table_id",
                schema: "public",
                table: "table_clocks",
                column: "table_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "blind_levels",
                schema: "public");

            migrationBuilder.DropTable(
                name: "table_clocks",
                schema: "public");
        }
    }
}
