// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Fix_Counterparty_SetNull : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_ledger_entries_table_players_counterparty_player_id",
                schema: "public",
                table: "ledger_entries");

            migrationBuilder.AddForeignKey(
                name: "fk_ledger_entries_table_players_counterparty_player_id",
                schema: "public",
                table: "ledger_entries",
                column: "counterparty_player_id",
                principalSchema: "public",
                principalTable: "table_players",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_ledger_entries_table_players_counterparty_player_id",
                schema: "public",
                table: "ledger_entries");

            migrationBuilder.AddForeignKey(
                name: "fk_ledger_entries_table_players_counterparty_player_id",
                schema: "public",
                table: "ledger_entries",
                column: "counterparty_player_id",
                principalSchema: "public",
                principalTable: "table_players",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
